### ISSUE TITLE
Enllaç a notícia?

### ISSUE THREAD

**Issue by robertgarrigos** [nigeon/la-llista-de-la-por#1]
Molt bona iniciativa. Crec que estaria bé afegir un enllaç a la notícia que corroborés el canvi de seu social. Com ho veus?

**Comment by nigeon** [comment]
Em sembla perfecte afegir-hi enllaços. Ja hi havia pensat, però no he tingut temps d'anar buscant massa més.
De fet, no fa falta que sigui una corroboració del canvi de seu. La idea està en recopilar aquelles empreses que clarament fan servir la seva força per atemorir (és una mica subjectiu, ho sé).
